/**
 * Prepress LPI Calibration Test Sheet Generator.
 * Generates an industry-standard 300 DPI test sheet covering 15 to 75 LPI
 * across different dot shapes and tonal gradients.
 */

export function generateLpiTestSheet(): HTMLCanvasElement {
  const canvas = document.createElement('canvas');
  // 300 DPI: 8 inches x 10 inches = 2400 x 3000 pixels (or 1600 x 2000 for high speed)
  const width = 1800;
  const height = 2400;
  canvas.width = width;
  canvas.height = height;

  const ctx = canvas.getContext('2d');
  if (!ctx) return canvas;

  // Background - pure white canvas (ready for film print)
  ctx.fillStyle = '#FFFFFF';
  ctx.fillRect(0, 0, width, height);

  // Border & registration marks
  ctx.strokeStyle = '#000000';
  ctx.lineWidth = 2;
  ctx.strokeRect(40, 40, width - 80, height - 80);

  // Corner registration targets
  drawRegistrationMark(ctx, 60, 60);
  drawRegistrationMark(ctx, width - 60, 60);
  drawRegistrationMark(ctx, 60, height - 60);
  drawRegistrationMark(ctx, width - 60, height - 60);

  // Title header
  ctx.fillStyle = '#000000';
  ctx.font = 'bold 36px Poppins, sans-serif';
  ctx.textAlign = 'center';
  ctx.fillText('HALFTONE PREPRESS LPI CALIBRATION SHEET', width / 2, 110);

  ctx.font = '500 20px Poppins, sans-serif';
  ctx.fillText('300 DPI NATIVE RESOLUTION · DTF / DTG / SCREEN PRINT VERIFICATION', width / 2, 145);

  // LPI Steps to display: 15, 25, 35, 45, 55, 65, 75
  const lpiSteps = [15, 25, 35, 45, 55, 65, 75];
  const startY = 200;
  const rowHeight = 280;

  lpiSteps.forEach((lpi, index) => {
    const y = startY + index * rowHeight;
    if (y + rowHeight > height - 100) return;

    // Row Label
    ctx.fillStyle = '#000000';
    ctx.font = 'bold 24px Poppins, sans-serif';
    ctx.textAlign = 'left';
    ctx.fillText(`${lpi} LPI`, 80, y + 40);

    ctx.font = '400 15px Poppins, sans-serif';
    ctx.fillText(lpi <= 35 ? 'Screen Print / Heavy Ink' : lpi <= 55 ? 'DTF Standard / Soft Hand' : 'High Detail DTG', 80, y + 65);

    // Render Gradient & Tonal Step Boxes for this LPI
    const boxStartX = 420;
    const boxWidth = width - boxStartX - 80;
    const boxHeight = 90;

    // Draw Continuous Gradient Bar
    drawHalftoneGradientBar(ctx, boxStartX, y + 10, boxWidth, boxHeight, lpi);

    // Draw Density Step Patches (10%, 25%, 50%, 75%, 90%)
    const steps = [0.1, 0.25, 0.5, 0.75, 0.9];
    const patchWidth = Math.floor(boxWidth / steps.length) - 10;
    const patchHeight = 80;
    const patchY = y + 115;

    steps.forEach((density, sIdx) => {
      const px = boxStartX + sIdx * (patchWidth + 10);
      drawHalftonePatch(ctx, px, patchY, patchWidth, patchHeight, lpi, density);
      
      // Patch label
      ctx.fillStyle = '#000000';
      ctx.font = '500 14px Poppins, sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText(`${Math.round(density * 100)}%`, px + patchWidth / 2, patchY + patchHeight + 20);
    });

    // Separator line
    ctx.strokeStyle = '#D1D5DB';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(80, y + rowHeight - 20);
    ctx.lineTo(width - 80, y + rowHeight - 20);
    ctx.stroke();
  });

  // Footer notes
  ctx.fillStyle = '#6B7280';
  ctx.font = '400 16px Poppins, sans-serif';
  ctx.textAlign = 'center';
  ctx.fillText('Generated by Halftone Studio Pro · Inspect printed dot formation with a 10x linen tester loupe', width / 2, height - 60);

  return canvas;
}

function drawRegistrationMark(ctx: CanvasRenderingContext2D, x: number, y: number) {
  ctx.save();
  ctx.strokeStyle = '#000000';
  ctx.lineWidth = 1.5;
  ctx.beginPath();
  ctx.arc(x, y, 16, 0, Math.PI * 2);
  ctx.moveTo(x - 24, y);
  ctx.lineTo(x + 24, y);
  ctx.moveTo(x, y - 24);
  ctx.lineTo(x, y + 24);
  ctx.stroke();
  ctx.restore();
}

function drawHalftoneGradientBar(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  lpi: number
) {
  const cellSize = Math.max(3, 300 / lpi);
  const angle = (45 * Math.PI) / 180;
  const cosA = Math.cos(angle);
  const sinA = Math.sin(angle);

  ctx.save();
  ctx.strokeRect(x, y, w, h);

  // We rasterize dots within the box
  const imgData = ctx.createImageData(w, h);
  const dst = imgData.data;

  for (let py = 0; py < h; py++) {
    for (let px = 0; px < w; px++) {
      const idx = (py * w + px) * 4;
      // Linear gradient across width (0.0 to 1.0)
      const density = px / w;

      const u = px * cosA - py * sinA;
      const v = px * sinA + py * cosA;

      const cu = (((u % cellSize) + cellSize) % cellSize) / cellSize - 0.5;
      const cv = (((v % cellSize) + cellSize) % cellSize) / cellSize - 0.5;
      const dist = Math.sqrt(cu * cu + cv * cv);

      const maxR = 0.55 * Math.sqrt(density);
      if (dist <= maxR) {
        dst[idx] = 0;
        dst[idx + 1] = 0;
        dst[idx + 2] = 0;
        dst[idx + 3] = 255;
      } else {
        dst[idx] = 255;
        dst[idx + 1] = 255;
        dst[idx + 2] = 255;
        dst[idx + 3] = 255;
      }
    }
  }

  ctx.putImageData(imgData, x, y);
  ctx.restore();
}

function drawHalftonePatch(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  lpi: number,
  density: number
) {
  const cellSize = Math.max(3, 300 / lpi);
  const angle = (45 * Math.PI) / 180;
  const cosA = Math.cos(angle);
  const sinA = Math.sin(angle);

  ctx.save();
  ctx.strokeRect(x, y, w, h);

  const imgData = ctx.createImageData(w, h);
  const dst = imgData.data;
  const maxR = 0.55 * Math.sqrt(density);

  for (let py = 0; py < h; py++) {
    for (let px = 0; px < w; px++) {
      const idx = (py * w + px) * 4;
      const u = px * cosA - py * sinA;
      const v = px * sinA + py * cosA;

      const cu = (((u % cellSize) + cellSize) % cellSize) / cellSize - 0.5;
      const cv = (((v % cellSize) + cellSize) % cellSize) / cellSize - 0.5;
      const dist = Math.sqrt(cu * cu + cv * cv);

      if (dist <= maxR) {
        dst[idx] = 0;
        dst[idx + 1] = 0;
        dst[idx + 2] = 0;
        dst[idx + 3] = 255;
      } else {
        dst[idx] = 255;
        dst[idx + 1] = 255;
        dst[idx + 2] = 255;
        dst[idx + 3] = 255;
      }
    }
  }

  ctx.putImageData(imgData, x, y);
  ctx.restore();
}
